# version: '3.8'

services:
  next-realworld-api-dev:
    container_name: next-realworld-api-dev
    image: next-realworld-api-dev
    build:
      context: .
      target: development
    depends_on:
      - next-realworld-mysql
    command: yarn start:dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
  next-realworld-mysql:
    container_name: ${DATABASE_HOST}
    image: mysql:9.3.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    expose:
      - ${DATABASE_PORT}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

networks:
  default:
    driver: bridge