export const USER_REPOSITORY = 'USER_REPOSITORY';
export const PROFILE_REPOSITORY = 'PROFILE_REPOSITORY';
export const FOLLOW_REPOSITORY = 'FOLLOW_REPOSITORY';
export const ARTICLE_REPOSITORY = 'ARTICLE_REPOSITORY';
export const DATA_SOURCE = 'DATA_SOURCE';
